#! /usr/bin/bash

mkdir basicbash;
cd basicbash;
touch index.html;
echo "Creating a new project";
echo "Hello World" > index.html;
mkdir css;
cd css;
touch stle.css;
cd ..;
mkdir js;
cd js;
touch app.js;
cd ..;
echo "All done!";
